name: Lint and Test Code

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  full-build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { arch: x86_64, on: ubuntu-latest }
        #- { arch: aarch64, on: ubuntu-24.04-arm }
    runs-on: "${{ matrix.platform.on }}"
    env:
      TARGET_ARCH: "${{ matrix.platform.arch }}"
    name: 'Full build and test linux-${{ matrix.platform.arch }}'
    steps:
      - name: harden runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # zizmor: ignore[stale-action-refs]
        with:
          components: rustfmt, clippy

      - name: cargo build
        run: cargo build

      - name: quality gate
        uses: ./.github/actions/quality-gate
